### ISSUE TITLE
New nav in ESS

### ISSUE THREAD

**Issue by nastasha-solomon** [elastic/security-docs#5066]
### Description

The main Security nav in ESS is being updated so it aligns with the main Security nav in Serverless. The updated nav will be available in 8.15 and only affects the ESS version of Security.

### Notes
- Users will have an option to revert back to the "classic" nav at any time. 
- Changes are being merged to 8.14, but they won't be available for customers until 8.15. There'll be additional work to clean up classic nav components after 8.14. I'm not sure what the doc impact of this work will be -- or if there will be any. Will need to sync with @semd on this.
- Check out the latest set of TH team demos for a demo of these changes.  

### Background & resources

* PRs: https://github.com/elastic/kibana/pull/179971
* Issues/metas: https://github.com/elastic/kibana/issues/179162
* Point of contact: @semd 
* Test environments: TBD - currently we'll have to add several feature flags to enable the new nav

### Issue template info

- Which documentation set does this change impact?  ESS only
- ESS release:  8.15
- Serverless release:  N/A
- Feature differences:  N/A? (confirm if the navs will truly be identical between ESS and serverless, or if any differences will still occur)
- API docs impact:  N/A
- Prerequisites, privileges, feature flags: Refer to related dev PR https://github.com/elastic/kibana/pull/179971:
    <details>
    <summary>Expand for feature flag details</summary>

    Unless we add the _kibana.yml_ configurations to enable the new navigation, the regular classic navigation will be displayed, it should keep working the same way without any change. The new landing pages (`Assets`, `Investigations`, `Machine Learning`,...), that exist only when using the new navigation, should not be accessible using the classic version.
    
    To enable the new navigation add the following _kibana.yml_ configs:
    ```
    xpack.cloud_integrations.experiments.enabled: true
    xpack.cloud_integrations.experiments.flag_overrides:
      "navigation.solutionNavEnabled": true
    
    xpack.cloud.id: "ftr_fake_cloud_id:aGVsbG8uY29tOjQ0MyRFUzEyM2FiYyRrYm4xMjNhYmM="
    xpack.cloud.base_url: "https://cloud.elastic.co"
    xpack.cloud.deployment_url: "/deployments/deploymentId"
    ```
    And enable the advanced setting
    
    ![image](https://github.com/elastic/kibana/assets/17747913/07e8952d-5bd5-4700-8105-7732f08de28e)
    </details>
